### ISSUE TITLE
Please provide route params for 'allow' function

### ISSUE THREAD

**Issue by Xetatronics** [neikvon/vue-role-manager#3]
Currently, 'allow' as a function has this signature:
```
// roles: current user roles
// route: current route object
roles: {
  allow: (roles, route) => {
    return ['role1', 'role2']
  }
}
```

It would be nice if this function get a third parameter containing the route parameters, which would make it possible to have routes like /user/42 where only user 42 has access to, if used like this:
```
path: '/user/:id',
roles: {
  allow: (roles, route, params) => {
    return params.id == getUserId() ? 'role1' : false
  }
}
```
Furthermore it would be awesome if this function is allowed to return true or false, where true means access is allowed, and false means it's not. This would make look the upper example even clearer:
```
path: '/user/:id',
roles: {
  allow: (roles, route, params) => params.id == getUserId()
}
```

Would be awesome to get that for this library!

**Comment by neikvon** [comment]
Can't find a good way to implement this currently.

PR welcome if you have.

**Comment by neikvon** [comment]
@Xetatronics Thanks for your PR. The tested version v1.2.0 was released, it should have fixed this issue.
