### ISSUE TITLE
v-roles directive are still not working

### ISSUE THREAD

**Issue by Xetatronics** [neikvon/vue-role-manager#4]
Thanks for fixing issue #2 but directives are still not working unfortunately.

vrm-directive.vue to prove the problem:
```
<template>
    <div>
        <!-- only create the button for 'admin' -->
        <button v-roles="['admin']">Admin Button</button>
        
        <!-- only create the button for 'user' -->
        <button v-roles="['user']">User Button</button>
    </div>
</template>

<script>
    import Vue from 'vue';
    
    export default {
        name: 'vrm-directive',
        created: () => {
            Vue.prototype.$vrm.setRoles(['user', 'admin']);
            console.log('Roles: ' + Vue.prototype.$vrm.getRoles());
        },
    };
</script>
```

In this example, the expected result would be that both buttons should be visible. But instead, you will notice that none of the buttons are visible. Why?

Thanks in advance if you can fix this issue :)

**Comment by neikvon** [comment]
@Xetatronics I'm sorry for forgetting to update the files in dist folder of npm package.
Please update to 'v1.1.2', thanks.
